### 1. To read the rounds2 and companies files, you would typically use Pandas read_csv function.

In [3]:
import pandas as pd

# Read the rounds2 file
rounds2 = pd.read_csv("rounds2.csv", encoding="ISO-8859-1")

# Read the companies file
companies = pd.read_csv("companies.txt", sep="\t", encoding="ISO-8859-1")

In [5]:
rounds2

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0
...,...,...,...,...,...,...
114944,/organization/zzzzapp-com,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,NaN,01-03-2014,41313.0
114945,/ORGANIZATION/ZZZZAPP-COM,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,NaN,01-05-2013,32842.0
114946,/organization/ãeron,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN
114947,/ORGANIZATION/ÃASYS-2,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,NaN,01-01-2015,18192.0
114948,/organization/ä°novatiff-reklam-ve-tanä±tä±m-h...,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,NaN,01-10-2013,14851.0

In [6]:
companies

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
...,...,...,...,...,...,...,...,...,...,...
66363,/Organization/Zznode-Science-And-Technology-Co...,ZZNode Science and Technology,http://www.zznode.com,Enterprise Software,operating,CHN,22,Beijing,Beijing,NaN
66364,/Organization/Zzzzapp-Com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
66365,/Organization/ÃÂEron,ÃÂERON,http://www.aeron.hu/,NaN,operating,NaN,NaN,NaN,NaN,01-01-2011
66366,/Organization/ÃâAsys-2,Ãâasys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
66367,/Organization/ÃÂ°Novatiff-Reklam-Ve-TanÃ¤Â±TÃ...,ÃÂ°novatiff Reklam ve TanÃÂ±tÃÂ±m Hizmetler...,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN

### 2. To find the number of unique companies in rounds2, you can use the nunique() function.

In [4]:
unique_rounds2_companies = rounds2['company_permalink'].nunique()

In [7]:
unique_rounds2_companies

90247

### 3. Similarly, for unique companies in the companies file:

In [8]:
unique_companies = companies['permalink'].nunique()

In [9]:
unique_companies

66368

### 4. To convert the permalink and company_permalink columns to uppercase:

In [10]:
companies['permalink'] = companies['permalink'].str.upper()
rounds2['company_permalink'] = rounds2['company_permalink'].str.upper()

In [11]:
companies['permalink']

0                                      /ORGANIZATION/-FAME
1                                   /ORGANIZATION/-QOUNTER
2                      /ORGANIZATION/-THE-ONE-OF-THEM-INC-
3                                    /ORGANIZATION/0-6-COM
4                           /ORGANIZATION/004-TECHNOLOGIES
                               ...
66363    /ORGANIZATION/ZZNODE-SCIENCE-AND-TECHNOLOGY-CO...
66364                            /ORGANIZATION/ZZZZAPP-COM
66365                               /ORGANIZATION/ÃÂERON
66366                            /ORGANIZATION/ÃÂASYS-2
66367    /ORGANIZATION/ÃÂ°NOVATIFF-REKLAM-VE-TANÃ¤Â±TÃ...
Name: permalink, Length: 66368, dtype: object

In [12]:
rounds2['company_permalink']

0                                       /ORGANIZATION/-FAME
1                                    /ORGANIZATION/-QOUNTER
2                                    /ORGANIZATION/-QOUNTER
3                       /ORGANIZATION/-THE-ONE-OF-THEM-INC-
4                                     /ORGANIZATION/0-6-COM
                                ...
114944                            /ORGANIZATION/ZZZZAPP-COM
114945                            /ORGANIZATION/ZZZZAPP-COM
114946                                 /ORGANIZATION/ÃERON
114947                               /ORGANIZATION/ÃASYS-2
114948    /ORGANIZATION/Ä°NOVATIFF-REKLAM-VE-TANÄ±TÄ±M-H...
Name: company_permalink, Length: 114949, dtype: object

### 5. To check if there are any companies in rounds2 not present in companies:

In [13]:
missing_companies = rounds2[~rounds2['company_permalink'].isin(companies['permalink'])]

In [14]:
missing_companies

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
77,/ORGANIZATION/10Â°NORTH,/funding-round/b41ff7de932f8b6e5bbeed3966c0ed6a,equity_crowdfunding,NaN,12-08-2014,NaN
729,/ORGANIZATION/51WOFANG-Æ Å¿§ÆÆ¿,/funding-round/346b9180d276a74e0fbb2825e66c6f5b,venture,A,06-07-2015,5000000.0
2670,/ORGANIZATION/ADSLINKEDÂ¢,/funding-round/449ae54bb63c768c232955ca6911dee4,seed,NaN,29-09-2014,100000.0
3166,/ORGANIZATION/AESTHETIC-EVERYTHINGÂ®-SOCIAL-NE...,/funding-round/62593455f1a69857ed05d5734cc04132,equity_crowdfunding,NaN,12-10-2014,NaN
3291,/ORGANIZATION/AFFLUENT-ATTACHÃ©-CLUB-2,/funding-round/626678bdf1654bc4df9b1b34647a4df1,seed,NaN,15-10-2014,100000.0
...,...,...,...,...,...,...
110545,/ORGANIZATION/WHODATÂS-SPACES,/funding-round/d5d6db3d1e6c54d71a63b3aa0c9278e6,seed,NaN,28-10-2014,30000.0
113839,/ORGANIZATION/ZENGAME-Ç¦ Æ¸¸Ç§Æ,/funding-round/6ba28fb4f3eadf5a9c6c81bc5dde6cdf,seed,NaN,17-07-2010,NaN
114946,/ORGANIZATION/ÃERON,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN
114947,/ORGANIZATION/ÃASYS-2,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,NaN,01-01-2015,18192.0
114948,/ORGANIZATION/Ä°NOVATIFF-REKLAM-VE-TANÄ±TÄ±M-H...,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,NaN,01-10-2013,14851.0

### 6. Merging the two dataframes:

In [15]:
master_frame = pd.merge(rounds2, companies, how='left', left_on='company_permalink', right_on='permalink')

# And to get the number of observations:

observations = master_frame.shape[0]

In [26]:
master_frame

,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at,raised_amount_category
0,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0,/ORGANIZATION/-FAME,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN,TypeC
1,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN,/ORGANIZATION/-QOUNTER,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014,TypeC
2,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0,/ORGANIZATION/-QOUNTER,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014,TypeA
3,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN,TypeA
4,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0,/ORGANIZATION/0-6-COM,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007,TypeA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114944,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,NaN,01-03-2014,41313.0,/ORGANIZATION/ZZZZAPP-COM,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012,TypeA
114945,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,NaN,01-05-2013,32842.0,/ORGANIZATION/ZZZZAPP-COM,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012,TypeA
114946,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TypeC
114947,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,NaN,01-01-2015,18192.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TypeA
114948,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,NaN,01-10-2013,14851.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TypeA

In [27]:
observations

114949

### 7. Dropping the redundant column:

In [16]:
master_frame.drop(columns=['company_permalink'], inplace=True)

### 8. To find the percentage of missing values and drop unnecessary columns:

In [17]:
missing_percentage = master_frame.isnull().mean() * 100
master_frame.dropna(axis=1, how='all', inplace=True)

In [28]:
missing_percentage

funding_round_permalink     0.000000
funding_round_type          0.000000
funding_round_code         72.909725
funded_at                   0.000000
raised_amount_usd          17.390321
permalink                   0.064376
name                        0.065246
homepage_url                5.393696
category_list               3.010900
status                      0.064376
country_code                7.578143
state_code                  9.549452
region                      8.873500
city                        8.870891
founded_at                 17.887933
dtype: float64

### 9. Creating a pivot table:

In [18]:
pivot_table = master_frame.pivot_table(values='raised_amount_usd', index='funding_round_type', aggfunc=['mean', 'median'])

In [29]:
pivot_table

                                   mean            median
                      raised_amount_usd raised_amount_usd
funding_round_type
angel                      9.586945e+05          400000.0
convertible_note           1.453439e+06          272000.0
debt_financing             1.704353e+07         1100000.0
equity_crowdfunding        5.383682e+05          100000.0
grant                      4.300576e+06          201684.0
non_equity_assistance      4.112031e+05           60000.0
post_ipo_debt              1.687046e+08        19950000.0
post_ipo_equity            8.218249e+07        12262852.5
private_equity             7.330859e+07        20000000.0
product_crowdfunding       1.363131e+06          183915.0
secondary_market           7.964963e+07        32600000.0
seed                       7.198180e+05          275000.0
undisclosed                1.924237e+07         1018680.0
venture                    1.174895e+07         5000000.0

### 10. Filtering master_frame based on raised_amount_usd:

In [20]:
filtered_master_frame = master_frame[(master_frame['raised_amount_usd'] >= 4000000) & (master_frame['raised_amount_usd'] <= 15000000)]

In [30]:
filtered_master_frame

,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0,/ORGANIZATION/-FAME,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
12,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,A,19-07-2014,8900000.0,/ORGANIZATION/0XDATA,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
21,/funding-round/11c228f58831bc7ed337ef69ecc560c2,private_equity,NaN,01-02-2015,6000000.0,/ORGANIZATION/1-800-PUBLICRELATIONS-INC-,"1-800-PublicRelations, Inc.",http://www.1800publicrelations.com,Internet Marketing|Media|Public Relations,operating,USA,NY,New York City,New York,24-10-2013
22,/funding-round/b952cbaf401f310927430c97b68162ea,venture,NaN,17-03-2015,5000000.0,/ORGANIZATION/1-MAINSTREAM,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012
28,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,A,09-10-2014,4000000.0,/ORGANIZATION/10-MINUTES-WITH,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114921,/funding-round/85443f5438bfd50104b9591eabc95c94,grant,NaN,26-03-2014,7500000.0,/ORGANIZATION/ZYOMYX-INC,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114922,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,NaN,11-07-2013,14219999.0,/ORGANIZATION/ZYOMYX-INC,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114930,/funding-round/c05aab2155e390066d51c6852ff61464,grant,NaN,11-09-2009,5400000.0,/ORGANIZATION/ZYRAZ-TECHNOLOGY,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114931,/funding-round/e949f077c943db197f20e43c2eb8d0e6,venture,A,09-10-2009,7991547.0,/ORGANIZATION/ZYRAZ-TECHNOLOGY,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114936,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,A,16-12-2004,8500000.0,/ORGANIZATION/ZYSTOR,Zystor,http://www.zystor.com,Biotechnology,acquired,USA,WI,Milwaukee,Milwaukee,NaN

### 11. Identifying top 9 countries in terms of highest investment in 'venture' fund type:

In [21]:
top_9_countries = master_frame[master_frame['funding_round_type'] == 'venture'].groupby('country_code')['raised_amount_usd'].sum().nlargest(9)

In [31]:
top_9_countries

country_code
USA    4.225108e+11
CHN    3.983542e+10
GBR    2.024563e+10
IND    1.439186e+10
CAN    9.583332e+09
FRA    7.241142e+09
ISR    6.907515e+09
DEU    6.345560e+09
JPN    3.363677e+09
Name: raised_amount_usd, dtype: float64

### 12. Creating the 'main_category' column:

In [25]:
# Define master_dataframe
master_dataframe = pd.merge(rounds2, companies, how='left', left_on='company_permalink', right_on='permalink')

# Define function to extract main category
def extract_main_category(category_list):
    if isinstance(category_list, str):
        return category_list.split('|')[0]
    else:
        return category_list

# Apply function to category_list column
master_dataframe['main_category'] = master_dataframe['category_list'].apply(extract_main_category)

In [32]:
master_dataframe['main_category']

0                         Media
1         Application Platforms
2         Application Platforms
3                          Apps
4                   Curated Web
                  ...
114944              Advertising
114945              Advertising
114946                      NaN
114947                      NaN
114948                      NaN
Name: main_category, Length: 114949, dtype: object

### 13. Converting 'raised_amount_usd' into categorical column:

In [23]:
def recode_amount(amount):
    if amount < 5000000:
        return 'TypeA'
    elif amount < 7000000:
        return 'TypeB'
    else:
        return 'TypeC'

master_frame['raised_amount_category'] = master_frame['raised_amount_usd'].apply(recode_amount)

In [33]:
master_frame['raised_amount_category']

0         TypeC
1         TypeC
2         TypeA
3         TypeA
4         TypeA
          ...
114944    TypeA
114945    TypeA
114946    TypeC
114947    TypeA
114948    TypeA
Name: raised_amount_category, Length: 114949, dtype: object